### ISSUE TITLE
bypasses

### ISSUE THREAD

**Issue by Dominance** [TinyModularThings/Player-Weight#1]
- [x] Horses and minecarts do not take in account for potion effects on players. Such as effects that slow down the players movement. Mining fatigue on a horse is still effected how ever.
- [x] Moveable modded containers that hold their content bypass the weight system all together. unless you assign a default weight value to the container such as 50. 
- [x] Shulker boxes, similar to modded containers.
- [x] Havent tested it yet with player-weight but jumping also bypasses a small portion of movement debuffs in iguana tweaks. so while the player could never get the jump jump jump speed boost. due to running being disabled they still get a minor boost to movement while jumping.

**Comment by Speiger** [comment]
Horses & Ridable things will be effected soon.
Yeah thats more of an issue by the mods. Ask the mod to make the Capability of the Inventory visible (Extra Utils does that already, i would have to implement for each mod a special compat to make that happen)
Shulker boxes are also handled in the next patch.
You can actually directly effect the movement & jump height by this and also constantly apply debufs to negate these problems.
