### ISSUE TITLE
Crash - Hard dependency on Useful Backpacks

### ISSUE THREAD

**Issue by Xorbah** [TinyModularThings/Player-Weight#12]
Title. Here's the log -

[crash-2019-05-11_18.28.19-client.txt](https://github.com/TinyModularThings/Player-Weight/files/3169538/crash-2019-05-11_18.28.19-client.txt)

**Comment by Speiger** [comment]
ok since i couldnt test the mod itself anyway because it caused forge errors on loadup i am going to remove that compat because i can not even test it properly. (Using the latest versions)

**Comment by Xorbah** [comment]
Wait, you're removing the compat for all of the backpack mods or just that specific one?

**Comment by Speiger** [comment]
that specific one
