### ISSUE TITLE
Player Weight Mod - Server Crash

### ISSUE THREAD

**Issue by Max039** [TinyModularThings/Player-Weight#15]
Hello there,

firstly I am sorry that I reported my issue wrongly. This is my first time every reporting an issue. Secondly I would like to thank you for your quick response.

--------------------------------------------------------------------------------

Situation : 
While I was trying to setup a modpack for myself through a lan-server I stumbeld across an error that keept my server from starting. Firstly I thought that the "Player Weight Mod" was not compatible with another mod. But even when I tried to start the server only with the "Player Weight Mod" it keept crashing.

I tried using the recommend forge version for 1.12.2 as well as the newest forge version 
( forge-1.12.2-14.23.5.2847-universal ).

Example error ( forge-1.12.2-14.23.5.2838-universal ) : 
https://pastebin.com/mQn5qaW0 

Yours sincerely
Max039

**Comment by Speiger** [comment]
It wasn't completly wrong. It is just not a good idea to spam a page with information. When it can be put into a link. So thats why I informed you.

Ok this is a new situation. You created a lan server with PWM? So created a new world and opened it to lan?
Or did you host a server that was in your house and linked it to your pc?
Like this is really important information for me so I actually can test the issue. (Replicating it helps a lot to find the "Actual" problem and not fix the symtom).

I hope my answer didn't come over to rude. And I hope I can fix that issue. It would be nice if you could provide the exact info.

Speiger.

**Comment by Max039** [comment]
Hey,
your answer wasn't rude at all ^^. I started a dedicated server seperatly on my computer. When I open my world on lan everything does function flawlessly.

Max039

**Comment by Speiger** [comment]
Ok I will look into it as soon my next bulk patching session comes in. (I have right now a lot of projects in work so it might take a couple days)

This issue will remind me of it so I won't forget.

**Comment by Max039** [comment]
Take your time, I appreciate your effort. :)

**Comment by Max039** [comment]
By any chance might there be a possiblity for a patch soon ? ^^

**Comment by Speiger** [comment]
oh i made a patch but forgot to fix that. I will patch that tomorrow.

**Comment by Max039** [comment]
Thanks for your effort :)

**Comment by Max039** [comment]
Short question : Can I find this patch on the curseforge site or where should I look ?

**Comment by Speiger** [comment]
patch is submitted on curse.

**Comment by Max039** [comment]
I am sorry to message you again but the server keeps crashing on startup just like before.

https://pastebin.com/GW9MUXkM

**Comment by Speiger** [comment]
hotfix released.

**Comment by Max039** [comment]
ty <3
