### ISSUE TITLE
PotionFile

### ISSUE THREAD

**Issue by planyte** [TinyModularThings/Player-Weight#19]
{
 "последствия": 
    [ 
        { 
            "type": "attribute",
            "Эффект": "generic.movementSpeed",
            "мин": 0,
            «макс»: 100,
            "проценты": правда,
            "id": "effect.moveSlowdown",
            "Количество": 1,
            "ModifierType": 2
        }
    ]
}
.

A player with a weight of 50kg does not slow down but even runs and walks faster.
How do I make a player walk more slowly at 50% of the weight load?

**Comment by Speiger** [comment]
language. thats why. it has all ot be in english. (at least the keys)

**Comment by planyte** [comment]
Последствия=Effects

**Comment by Speiger** [comment]
Yeah you still need to write this in english.
My tool does only check for the english words in the Keys.
so Effects has to be named effects because its checking for effects not Последствия

**Comment by planyte** [comment]
Yes I wrote it in English it's just a translator translated it

**Comment by Speiger** [comment]
Ok this is pretty hidden do to curse not liking code really well but here is a example one that i copied out of the example sheet for Effect on the cursepage.

```json
{
	"effects": 
	[ 
		{ 
			"type": "potion", 
			"cooldown": "20", 
			"min": 1, 
			"max": 200, 
			"potions": 
			[ 
				{ 
					"name": "minecraft:speed", 
					"duration": "40", 
					"amplifier": 1 
				} 
			] 
		} 
	] 
}
```
This is how the stuff has to look like uppercase and lowercase matter too. why do you think i typed these names how i typed them
