### ISSUE TITLE
[Suggestion] Effects affecting mobs

### ISSUE THREAD

**Issue by Snownee** [TinyModularThings/Player-Weight#7]
Player Weight is amazing but there is a problem that players can simply put their items into donkey's inventory and lead them. The penalties are completely invalid. So I think allowing effects on some specific mobs could be a better way.

**Comment by Speiger** [comment]
Yes that is true, on the other hand you have to transport a donkey which is a lot harder and annoying then just riding it. (Also it is a good transportation way too)
the idea of penalties is for cheating the system, Aka: Putting everything into the donkey & riding it away.
While putting it into the donkey &  and going with it is still valid.
