### ISSUE TITLE
Max weight resetting on death (I have TombManyGraves)

### ISSUE THREAD

**Issue by euphoniumlover** [TinyModularThings/Player-Weight#8]
Before I died, my max was 245.0Kg, but after I died, I had 0mg max weight. As I said, TombManyGraves is installed. Is this a problem, TombManyGraves, or is it something else? On the config it still says 
`D:max_weight:240.0`

**Comment by euphoniumlover** [comment]
Exiting and re-entering the world fixes the problem. It's on a per-session business

**Comment by Speiger** [comment]
Hmmm not sure.

**Comment by Speiger** [comment]
Ok its fixed. Patch is waiting on curse validation.
